// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ghlbipuqoyntnprulxda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdobGJpcHVxb3ludG5wcnVseGRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMTY0NzcsImV4cCI6MjA2NDg5MjQ3N30.4nS6B9Fas4I93eRmY0H5Rvg28UbJpVQEGTIN9APKd64";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);